spring:
  datasource:
    url: jdbc:h2:file:~/.config/atv/data
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: update
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  cache:
    type: redis
  redis:
    host: 192.168.2.101
    port: 6379
    password: 123456
    timeout: 3000

server:
  error:
    include-message: always
  port: 9091

cn:
  spark2fire:
    auth:
      jwt:
        secret-key: "27b8c0a5-ed89-45cb-b5fd-cae6af9be6d7"

app:
  configUrl:
  sort: true
  formats:
    - dff
    - dsf
    - mp3
    - aac
    - wav
    - wma
    - cda
    - flac
    - m4a
    - mid
    - mka
    - mp2
    - mpa
    - mpc
    - ape
    - ofr
    - ogg
    - ra
    - wv
    - tta
    - ac3
    - dts
    - tak
    - webm
    - wmv
    - mpeg
    - mov
    - ram
    - swf
    - mp4
    - avi
    - rm
    - rmvb
    - flv
    - mpg
    - mkv
    - m3u8
    - ts
    - 3gp
    - asf
  sites:
    - name: xy
      url: ${ALIST_URL:http://192.168.2.101:5678}
#      indexFile: https://hhzhome.accesscam.org:32443/files/index.txt
      indexFile: http://192.168.2.101:9092/files/index.txt
      searchable: true
      version: 3
    - name: me
      url: ${ALIST_URL:http://192.168.2.101:5244}
      searchable: true
      version: 3

